### ISSUE TITLE
Seems like this has been broken for a while

### ISSUE THREAD

**Issue by machty** [supercollider-quarks/Spectrogram#2]
I'm still running into the issue described here: https://github.com/supercollider/supercollider/issues/296

**Comment by jamshark70** [comment]
`Image` has been implemented for Qt, but its interface is probably a bit different from the calls used in this several-years-old code now. There probably are some errors for that reason.

The original developers of this quark are much less active now than they used to be. (Btw if you check the commit history here -- https://github.com/supercollider-quarks/Spectrogram/commits/master -- you can see a few minor cleanup commits in the last few years, but no significant development since 2010.)

So it's probably going to be up to some enterprising user to take the lead on this: check the uses of "image" in the .sc files here and find equivalents in the new Image class.
